services:
  db:
    image: postgres:16.9
    container_name: kotlin_pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cache-fee-api-db
      POSTGRES_USER: cache-fee-api-user
      POSTGRES_PASSWORD: cache-fee-api-password
    volumes:
      - cache-fee-api-db-volume:/var/lib/postgresql/data

  restate:
    image: docker.restate.dev/restatedev/restate:1.3
    container_name: restate_dev
    ports:
      - "8080:8080"   # Durable service requests
      - "9070:9070"   # Restate Web UI
      - "9071:9071"   # Internal communication
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  cache-fee-api-db-volume:
