ktor:
    application:
        modules:
            - com.alsoug.ApplicationKt.module
    deployment:
        port: 8765
postgres:
    url: "jdbc:postgresql://localhost:5432/cache-fee-api-db"
    user: cache-fee-api-user
    password: cache-fee-api-password